// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message/5/proto/building.proto

package building;

public final class BuildingOuterClass {
  private BuildingOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BuildingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:building.Building)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string building_name = 1;</code>
     * @return The buildingName.
     */
    java.lang.String getBuildingName();
    /**
     * <code>string building_name = 1;</code>
     * @return The bytes for buildingName.
     */
    com.google.protobuf.ByteString
        getBuildingNameBytes();

    /**
     * <code>int32 building_number = 2;</code>
     * @return The buildingNumber.
     */
    int getBuildingNumber();

    /**
     * <code>.street.Street street = 3;</code>
     * @return Whether the street field is set.
     */
    boolean hasStreet();
    /**
     * <code>.street.Street street = 3;</code>
     * @return The street.
     */
    street.StreetOuterClass.Street getStreet();
    /**
     * <code>.street.Street street = 3;</code>
     */
    street.StreetOuterClass.StreetOrBuilder getStreetOrBuilder();
  }
  /**
   * Protobuf type {@code building.Building}
   */
  public static final class Building extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:building.Building)
      BuildingOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Building.newBuilder() to construct.
    private Building(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Building() {
      buildingName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Building();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Building(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              buildingName_ = s;
              break;
            }
            case 16: {

              buildingNumber_ = input.readInt32();
              break;
            }
            case 26: {
              street.StreetOuterClass.Street.Builder subBuilder = null;
              if (street_ != null) {
                subBuilder = street_.toBuilder();
              }
              street_ = input.readMessage(street.StreetOuterClass.Street.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(street_);
                street_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return building.BuildingOuterClass.internal_static_building_Building_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return building.BuildingOuterClass.internal_static_building_Building_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              building.BuildingOuterClass.Building.class, building.BuildingOuterClass.Building.Builder.class);
    }

    public static final int BUILDING_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object buildingName_;
    /**
     * <code>string building_name = 1;</code>
     * @return The buildingName.
     */
    @java.lang.Override
    public java.lang.String getBuildingName() {
      java.lang.Object ref = buildingName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        buildingName_ = s;
        return s;
      }
    }
    /**
     * <code>string building_name = 1;</code>
     * @return The bytes for buildingName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBuildingNameBytes() {
      java.lang.Object ref = buildingName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        buildingName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BUILDING_NUMBER_FIELD_NUMBER = 2;
    private int buildingNumber_;
    /**
     * <code>int32 building_number = 2;</code>
     * @return The buildingNumber.
     */
    @java.lang.Override
    public int getBuildingNumber() {
      return buildingNumber_;
    }

    public static final int STREET_FIELD_NUMBER = 3;
    private street.StreetOuterClass.Street street_;
    /**
     * <code>.street.Street street = 3;</code>
     * @return Whether the street field is set.
     */
    @java.lang.Override
    public boolean hasStreet() {
      return street_ != null;
    }
    /**
     * <code>.street.Street street = 3;</code>
     * @return The street.
     */
    @java.lang.Override
    public street.StreetOuterClass.Street getStreet() {
      return street_ == null ? street.StreetOuterClass.Street.getDefaultInstance() : street_;
    }
    /**
     * <code>.street.Street street = 3;</code>
     */
    @java.lang.Override
    public street.StreetOuterClass.StreetOrBuilder getStreetOrBuilder() {
      return getStreet();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getBuildingNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, buildingName_);
      }
      if (buildingNumber_ != 0) {
        output.writeInt32(2, buildingNumber_);
      }
      if (street_ != null) {
        output.writeMessage(3, getStreet());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getBuildingNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, buildingName_);
      }
      if (buildingNumber_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, buildingNumber_);
      }
      if (street_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getStreet());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof building.BuildingOuterClass.Building)) {
        return super.equals(obj);
      }
      building.BuildingOuterClass.Building other = (building.BuildingOuterClass.Building) obj;

      if (!getBuildingName()
          .equals(other.getBuildingName())) return false;
      if (getBuildingNumber()
          != other.getBuildingNumber()) return false;
      if (hasStreet() != other.hasStreet()) return false;
      if (hasStreet()) {
        if (!getStreet()
            .equals(other.getStreet())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BUILDING_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getBuildingName().hashCode();
      hash = (37 * hash) + BUILDING_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getBuildingNumber();
      if (hasStreet()) {
        hash = (37 * hash) + STREET_FIELD_NUMBER;
        hash = (53 * hash) + getStreet().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static building.BuildingOuterClass.Building parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static building.BuildingOuterClass.Building parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static building.BuildingOuterClass.Building parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static building.BuildingOuterClass.Building parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static building.BuildingOuterClass.Building parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static building.BuildingOuterClass.Building parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static building.BuildingOuterClass.Building parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static building.BuildingOuterClass.Building parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static building.BuildingOuterClass.Building parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static building.BuildingOuterClass.Building parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static building.BuildingOuterClass.Building parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static building.BuildingOuterClass.Building parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(building.BuildingOuterClass.Building prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code building.Building}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:building.Building)
        building.BuildingOuterClass.BuildingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return building.BuildingOuterClass.internal_static_building_Building_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return building.BuildingOuterClass.internal_static_building_Building_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                building.BuildingOuterClass.Building.class, building.BuildingOuterClass.Building.Builder.class);
      }

      // Construct using building.BuildingOuterClass.Building.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        buildingName_ = "";

        buildingNumber_ = 0;

        if (streetBuilder_ == null) {
          street_ = null;
        } else {
          street_ = null;
          streetBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return building.BuildingOuterClass.internal_static_building_Building_descriptor;
      }

      @java.lang.Override
      public building.BuildingOuterClass.Building getDefaultInstanceForType() {
        return building.BuildingOuterClass.Building.getDefaultInstance();
      }

      @java.lang.Override
      public building.BuildingOuterClass.Building build() {
        building.BuildingOuterClass.Building result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public building.BuildingOuterClass.Building buildPartial() {
        building.BuildingOuterClass.Building result = new building.BuildingOuterClass.Building(this);
        result.buildingName_ = buildingName_;
        result.buildingNumber_ = buildingNumber_;
        if (streetBuilder_ == null) {
          result.street_ = street_;
        } else {
          result.street_ = streetBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof building.BuildingOuterClass.Building) {
          return mergeFrom((building.BuildingOuterClass.Building)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(building.BuildingOuterClass.Building other) {
        if (other == building.BuildingOuterClass.Building.getDefaultInstance()) return this;
        if (!other.getBuildingName().isEmpty()) {
          buildingName_ = other.buildingName_;
          onChanged();
        }
        if (other.getBuildingNumber() != 0) {
          setBuildingNumber(other.getBuildingNumber());
        }
        if (other.hasStreet()) {
          mergeStreet(other.getStreet());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        building.BuildingOuterClass.Building parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (building.BuildingOuterClass.Building) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object buildingName_ = "";
      /**
       * <code>string building_name = 1;</code>
       * @return The buildingName.
       */
      public java.lang.String getBuildingName() {
        java.lang.Object ref = buildingName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          buildingName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string building_name = 1;</code>
       * @return The bytes for buildingName.
       */
      public com.google.protobuf.ByteString
          getBuildingNameBytes() {
        java.lang.Object ref = buildingName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          buildingName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string building_name = 1;</code>
       * @param value The buildingName to set.
       * @return This builder for chaining.
       */
      public Builder setBuildingName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        buildingName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string building_name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBuildingName() {
        
        buildingName_ = getDefaultInstance().getBuildingName();
        onChanged();
        return this;
      }
      /**
       * <code>string building_name = 1;</code>
       * @param value The bytes for buildingName to set.
       * @return This builder for chaining.
       */
      public Builder setBuildingNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        buildingName_ = value;
        onChanged();
        return this;
      }

      private int buildingNumber_ ;
      /**
       * <code>int32 building_number = 2;</code>
       * @return The buildingNumber.
       */
      @java.lang.Override
      public int getBuildingNumber() {
        return buildingNumber_;
      }
      /**
       * <code>int32 building_number = 2;</code>
       * @param value The buildingNumber to set.
       * @return This builder for chaining.
       */
      public Builder setBuildingNumber(int value) {
        
        buildingNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 building_number = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBuildingNumber() {
        
        buildingNumber_ = 0;
        onChanged();
        return this;
      }

      private street.StreetOuterClass.Street street_;
      private com.google.protobuf.SingleFieldBuilderV3<
          street.StreetOuterClass.Street, street.StreetOuterClass.Street.Builder, street.StreetOuterClass.StreetOrBuilder> streetBuilder_;
      /**
       * <code>.street.Street street = 3;</code>
       * @return Whether the street field is set.
       */
      public boolean hasStreet() {
        return streetBuilder_ != null || street_ != null;
      }
      /**
       * <code>.street.Street street = 3;</code>
       * @return The street.
       */
      public street.StreetOuterClass.Street getStreet() {
        if (streetBuilder_ == null) {
          return street_ == null ? street.StreetOuterClass.Street.getDefaultInstance() : street_;
        } else {
          return streetBuilder_.getMessage();
        }
      }
      /**
       * <code>.street.Street street = 3;</code>
       */
      public Builder setStreet(street.StreetOuterClass.Street value) {
        if (streetBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          street_ = value;
          onChanged();
        } else {
          streetBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.street.Street street = 3;</code>
       */
      public Builder setStreet(
          street.StreetOuterClass.Street.Builder builderForValue) {
        if (streetBuilder_ == null) {
          street_ = builderForValue.build();
          onChanged();
        } else {
          streetBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.street.Street street = 3;</code>
       */
      public Builder mergeStreet(street.StreetOuterClass.Street value) {
        if (streetBuilder_ == null) {
          if (street_ != null) {
            street_ =
              street.StreetOuterClass.Street.newBuilder(street_).mergeFrom(value).buildPartial();
          } else {
            street_ = value;
          }
          onChanged();
        } else {
          streetBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.street.Street street = 3;</code>
       */
      public Builder clearStreet() {
        if (streetBuilder_ == null) {
          street_ = null;
          onChanged();
        } else {
          street_ = null;
          streetBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.street.Street street = 3;</code>
       */
      public street.StreetOuterClass.Street.Builder getStreetBuilder() {
        
        onChanged();
        return getStreetFieldBuilder().getBuilder();
      }
      /**
       * <code>.street.Street street = 3;</code>
       */
      public street.StreetOuterClass.StreetOrBuilder getStreetOrBuilder() {
        if (streetBuilder_ != null) {
          return streetBuilder_.getMessageOrBuilder();
        } else {
          return street_ == null ?
              street.StreetOuterClass.Street.getDefaultInstance() : street_;
        }
      }
      /**
       * <code>.street.Street street = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          street.StreetOuterClass.Street, street.StreetOuterClass.Street.Builder, street.StreetOuterClass.StreetOrBuilder> 
          getStreetFieldBuilder() {
        if (streetBuilder_ == null) {
          streetBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              street.StreetOuterClass.Street, street.StreetOuterClass.Street.Builder, street.StreetOuterClass.StreetOrBuilder>(
                  getStreet(),
                  getParentForChildren(),
                  isClean());
          street_ = null;
        }
        return streetBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:building.Building)
    }

    // @@protoc_insertion_point(class_scope:building.Building)
    private static final building.BuildingOuterClass.Building DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new building.BuildingOuterClass.Building();
    }

    public static building.BuildingOuterClass.Building getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Building>
        PARSER = new com.google.protobuf.AbstractParser<Building>() {
      @java.lang.Override
      public Building parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Building(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Building> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Building> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public building.BuildingOuterClass.Building getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_building_Building_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_building_Building_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036message/5/proto/building.proto\022\010buildi" +
      "ng\032\034message/5/proto/street.proto\"Z\n\010Buil" +
      "ding\022\025\n\rbuilding_name\030\001 \001(\t\022\027\n\017building_" +
      "number\030\002 \001(\005\022\036\n\006street\030\003 \001(\0132\016.street.St" +
      "reetb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          street.StreetOuterClass.getDescriptor(),
        });
    internal_static_building_Building_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_building_Building_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_building_Building_descriptor,
        new java.lang.String[] { "BuildingName", "BuildingNumber", "Street", });
    street.StreetOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
