// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message/5/proto/street.proto

package street;

public final class StreetOuterClass {
  private StreetOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StreetOrBuilder extends
      // @@protoc_insertion_point(interface_extends:street.Street)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string street_name = 1;</code>
     * @return The streetName.
     */
    java.lang.String getStreetName();
    /**
     * <code>string street_name = 1;</code>
     * @return The bytes for streetName.
     */
    com.google.protobuf.ByteString
        getStreetNameBytes();

    /**
     * <code>.city.City city = 2;</code>
     * @return Whether the city field is set.
     */
    boolean hasCity();
    /**
     * <code>.city.City city = 2;</code>
     * @return The city.
     */
    city.CityOuterClass.City getCity();
    /**
     * <code>.city.City city = 2;</code>
     */
    city.CityOuterClass.CityOrBuilder getCityOrBuilder();
  }
  /**
   * Protobuf type {@code street.Street}
   */
  public static final class Street extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:street.Street)
      StreetOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Street.newBuilder() to construct.
    private Street(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Street() {
      streetName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Street();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Street(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              streetName_ = s;
              break;
            }
            case 18: {
              city.CityOuterClass.City.Builder subBuilder = null;
              if (city_ != null) {
                subBuilder = city_.toBuilder();
              }
              city_ = input.readMessage(city.CityOuterClass.City.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(city_);
                city_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return street.StreetOuterClass.internal_static_street_Street_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return street.StreetOuterClass.internal_static_street_Street_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              street.StreetOuterClass.Street.class, street.StreetOuterClass.Street.Builder.class);
    }

    public static final int STREET_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object streetName_;
    /**
     * <code>string street_name = 1;</code>
     * @return The streetName.
     */
    @java.lang.Override
    public java.lang.String getStreetName() {
      java.lang.Object ref = streetName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        streetName_ = s;
        return s;
      }
    }
    /**
     * <code>string street_name = 1;</code>
     * @return The bytes for streetName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStreetNameBytes() {
      java.lang.Object ref = streetName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        streetName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CITY_FIELD_NUMBER = 2;
    private city.CityOuterClass.City city_;
    /**
     * <code>.city.City city = 2;</code>
     * @return Whether the city field is set.
     */
    @java.lang.Override
    public boolean hasCity() {
      return city_ != null;
    }
    /**
     * <code>.city.City city = 2;</code>
     * @return The city.
     */
    @java.lang.Override
    public city.CityOuterClass.City getCity() {
      return city_ == null ? city.CityOuterClass.City.getDefaultInstance() : city_;
    }
    /**
     * <code>.city.City city = 2;</code>
     */
    @java.lang.Override
    public city.CityOuterClass.CityOrBuilder getCityOrBuilder() {
      return getCity();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getStreetNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, streetName_);
      }
      if (city_ != null) {
        output.writeMessage(2, getCity());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getStreetNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, streetName_);
      }
      if (city_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getCity());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof street.StreetOuterClass.Street)) {
        return super.equals(obj);
      }
      street.StreetOuterClass.Street other = (street.StreetOuterClass.Street) obj;

      if (!getStreetName()
          .equals(other.getStreetName())) return false;
      if (hasCity() != other.hasCity()) return false;
      if (hasCity()) {
        if (!getCity()
            .equals(other.getCity())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STREET_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getStreetName().hashCode();
      if (hasCity()) {
        hash = (37 * hash) + CITY_FIELD_NUMBER;
        hash = (53 * hash) + getCity().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static street.StreetOuterClass.Street parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static street.StreetOuterClass.Street parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static street.StreetOuterClass.Street parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static street.StreetOuterClass.Street parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static street.StreetOuterClass.Street parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static street.StreetOuterClass.Street parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static street.StreetOuterClass.Street parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static street.StreetOuterClass.Street parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static street.StreetOuterClass.Street parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static street.StreetOuterClass.Street parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static street.StreetOuterClass.Street parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static street.StreetOuterClass.Street parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(street.StreetOuterClass.Street prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code street.Street}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:street.Street)
        street.StreetOuterClass.StreetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return street.StreetOuterClass.internal_static_street_Street_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return street.StreetOuterClass.internal_static_street_Street_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                street.StreetOuterClass.Street.class, street.StreetOuterClass.Street.Builder.class);
      }

      // Construct using street.StreetOuterClass.Street.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        streetName_ = "";

        if (cityBuilder_ == null) {
          city_ = null;
        } else {
          city_ = null;
          cityBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return street.StreetOuterClass.internal_static_street_Street_descriptor;
      }

      @java.lang.Override
      public street.StreetOuterClass.Street getDefaultInstanceForType() {
        return street.StreetOuterClass.Street.getDefaultInstance();
      }

      @java.lang.Override
      public street.StreetOuterClass.Street build() {
        street.StreetOuterClass.Street result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public street.StreetOuterClass.Street buildPartial() {
        street.StreetOuterClass.Street result = new street.StreetOuterClass.Street(this);
        result.streetName_ = streetName_;
        if (cityBuilder_ == null) {
          result.city_ = city_;
        } else {
          result.city_ = cityBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof street.StreetOuterClass.Street) {
          return mergeFrom((street.StreetOuterClass.Street)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(street.StreetOuterClass.Street other) {
        if (other == street.StreetOuterClass.Street.getDefaultInstance()) return this;
        if (!other.getStreetName().isEmpty()) {
          streetName_ = other.streetName_;
          onChanged();
        }
        if (other.hasCity()) {
          mergeCity(other.getCity());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        street.StreetOuterClass.Street parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (street.StreetOuterClass.Street) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object streetName_ = "";
      /**
       * <code>string street_name = 1;</code>
       * @return The streetName.
       */
      public java.lang.String getStreetName() {
        java.lang.Object ref = streetName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          streetName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string street_name = 1;</code>
       * @return The bytes for streetName.
       */
      public com.google.protobuf.ByteString
          getStreetNameBytes() {
        java.lang.Object ref = streetName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          streetName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string street_name = 1;</code>
       * @param value The streetName to set.
       * @return This builder for chaining.
       */
      public Builder setStreetName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        streetName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string street_name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStreetName() {
        
        streetName_ = getDefaultInstance().getStreetName();
        onChanged();
        return this;
      }
      /**
       * <code>string street_name = 1;</code>
       * @param value The bytes for streetName to set.
       * @return This builder for chaining.
       */
      public Builder setStreetNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        streetName_ = value;
        onChanged();
        return this;
      }

      private city.CityOuterClass.City city_;
      private com.google.protobuf.SingleFieldBuilderV3<
          city.CityOuterClass.City, city.CityOuterClass.City.Builder, city.CityOuterClass.CityOrBuilder> cityBuilder_;
      /**
       * <code>.city.City city = 2;</code>
       * @return Whether the city field is set.
       */
      public boolean hasCity() {
        return cityBuilder_ != null || city_ != null;
      }
      /**
       * <code>.city.City city = 2;</code>
       * @return The city.
       */
      public city.CityOuterClass.City getCity() {
        if (cityBuilder_ == null) {
          return city_ == null ? city.CityOuterClass.City.getDefaultInstance() : city_;
        } else {
          return cityBuilder_.getMessage();
        }
      }
      /**
       * <code>.city.City city = 2;</code>
       */
      public Builder setCity(city.CityOuterClass.City value) {
        if (cityBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          city_ = value;
          onChanged();
        } else {
          cityBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.city.City city = 2;</code>
       */
      public Builder setCity(
          city.CityOuterClass.City.Builder builderForValue) {
        if (cityBuilder_ == null) {
          city_ = builderForValue.build();
          onChanged();
        } else {
          cityBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.city.City city = 2;</code>
       */
      public Builder mergeCity(city.CityOuterClass.City value) {
        if (cityBuilder_ == null) {
          if (city_ != null) {
            city_ =
              city.CityOuterClass.City.newBuilder(city_).mergeFrom(value).buildPartial();
          } else {
            city_ = value;
          }
          onChanged();
        } else {
          cityBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.city.City city = 2;</code>
       */
      public Builder clearCity() {
        if (cityBuilder_ == null) {
          city_ = null;
          onChanged();
        } else {
          city_ = null;
          cityBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.city.City city = 2;</code>
       */
      public city.CityOuterClass.City.Builder getCityBuilder() {
        
        onChanged();
        return getCityFieldBuilder().getBuilder();
      }
      /**
       * <code>.city.City city = 2;</code>
       */
      public city.CityOuterClass.CityOrBuilder getCityOrBuilder() {
        if (cityBuilder_ != null) {
          return cityBuilder_.getMessageOrBuilder();
        } else {
          return city_ == null ?
              city.CityOuterClass.City.getDefaultInstance() : city_;
        }
      }
      /**
       * <code>.city.City city = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          city.CityOuterClass.City, city.CityOuterClass.City.Builder, city.CityOuterClass.CityOrBuilder> 
          getCityFieldBuilder() {
        if (cityBuilder_ == null) {
          cityBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              city.CityOuterClass.City, city.CityOuterClass.City.Builder, city.CityOuterClass.CityOrBuilder>(
                  getCity(),
                  getParentForChildren(),
                  isClean());
          city_ = null;
        }
        return cityBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:street.Street)
    }

    // @@protoc_insertion_point(class_scope:street.Street)
    private static final street.StreetOuterClass.Street DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new street.StreetOuterClass.Street();
    }

    public static street.StreetOuterClass.Street getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Street>
        PARSER = new com.google.protobuf.AbstractParser<Street>() {
      @java.lang.Override
      public Street parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Street(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Street> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Street> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public street.StreetOuterClass.Street getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_street_Street_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_street_Street_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034message/5/proto/street.proto\022\006street\032\032" +
      "message/5/proto/city.proto\"7\n\006Street\022\023\n\013" +
      "street_name\030\001 \001(\t\022\030\n\004city\030\002 \001(\0132\n.city.C" +
      "ityb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          city.CityOuterClass.getDescriptor(),
        });
    internal_static_street_Street_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_street_Street_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_street_Street_descriptor,
        new java.lang.String[] { "StreetName", "City", });
    city.CityOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
